;; Reference
;; http://blog.nacyot.com/articles/2014-06-01-emacs-with-cask/

(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "https://marmalade-repo.org/packages/")
(source "SC" "http://joseito.republika.pl/sunrise-commander/")
(source "org" "http://orgmode.org/elpa/")


;; sample
(depends-on "cask")
(depends-on "auto-complete")
(depends-on "dash")
(depends-on "f")
(depends-on "flycheck")
(depends-on "helm")
(depends-on "popup")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "yasnippet")
(depends-on "color-theme")

;; document
(depends-on "markdown-mode")

;; ide
(depends-on "highlight-current-line")
(depends-on "rainbow-delimiters")
(depends-on "w3")
(depends-on "cmake-mode")
(depends-on "color-theme")

;; ruby
(depends-on "ruby-end")
(depends-on "rspec-mode")
(depends-on "ruby-additional")
(depends-on "ruby-block")

;; web
(depends-on "web-mode")
(depends-on "slim-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "yaml-mode")

;; python
(depends-on "jinja2-mode")
(depends-on "jedi")

;; javascript
(depends-on "coffee-mode")
(depends-on "json-mode")
(depends-on "typescript-mode")

;; haskell
(depends-on "haskell-mode")
(depends-on "ghc")

;; scheme / racket
(depends-on "scheme-complete")
(depends-on "racket-mode")

;; sql
(depends-on "esqlite")
(depends-on "sql-indent")

;; go
(depends-on "go-mode")
(depends-on "go-autocomplete")
(depends-on "go-eldoc")

;; etc language
(depends-on "io-mode")
(depends-on "erlang")
(depends-on "clojure-mode")
(depends-on "scala-mode2")
(depends-on "dockerfile-mode")
(depends-on "csharp-mode")
(depends-on "php-mode")

;; auto-complete with company
(depends-on "company")
(depends-on "company-go")

;; misc
(depends-on "cloc")
(depends-on "twittering-mode")

;; git
(depends-on "gitattributes-mode")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")

;; maagit require emacs 24.4
;;(depends-on "magit")
