#!/bin/sh
# http://pygments.org/docs/formatters/
OPTIONS="-f terminal"

case "$1" in
	*.awk|*.groff|*.java|*.js|*.m4|*.php|*.pl|*.pm|*.pod|*.sh|\
	*.ts|*.tsx|*.jsx|\
	*.yaml|*.json|\
	*.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
	*.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
	*.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass)
		pygmentize $OPTIONS "$1";;
	.bashrc|.bash_aliases|.bash_environment)
		pygmentize $OPTIONS -l sh "$1"
		;;
	*)
		grep "#\!/bin/bash" "$1" > /dev/null
		if [ "$?" -eq "0" ]; then
			pygmentize $OPTIONS -l sh "$1"
		else
			exit 1
		fi
esac

exit 0
